spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/313715295/config-repo.git
          basedir: F:\idea-workspace\spring_cloud_demo\config
#         因为电脑已经存储了git的账号密码，所以这里不需要配置，如果没有的话还是需要的
#          username:
#          password:
server:
  port: 8866
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/